apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeledger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeledger.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeledger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubeledger.fullname" . }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeledger.fullname" . }}
  labels:
    {{- include "kubeledger.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - nodes/stats
  - pods
  verbs:
  - get
  - list
  - watch
{{- if .Values.securityContext.openshift }}
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot-v2
{{- if not .Values.dataVolume.persist }}
  - hostaccess
{{- end }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeledger.fullname" . }}
  labels:
    {{- include "kubeledger.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeledger.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeledger.fullname" . }}
  namespace: {{ .Release.Namespace }}
