---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeledger

resources:
  - resources/kubeledger-namespace.yaml
  - resources/kubeledger-rbac.yaml
  - resources/kubeledger-config.yaml
  - resources/kubeledger-secrets.yaml
  - resources/kubeledger-sts.yaml
  - resources/kubeledger-service.yaml
  - resources/kubeledger-tests.yaml
images:
  - name: kubeledger
    newName: ghcr.io/realopslabs/kubeledger
    newTag: 26.01.1
