apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-opex-analytics-config
data:
  KOA_COST_MODEL: 'CUMULATIVE_RATIO'
  KOA_BILLING_HOURLY_RATE: '0.0'
  KOA_BILLING_CURRENCY_SYMBOL: '$'
  KOA_K8S_API_ENDPOINT: 'https://kubernetes.default'
  KOA_K8S_API_VERIFY_SSL: 'true'
  KOA_K8S_CACERT: '/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  KOA_INCLUDED_NAMESPACES: ''
  KOA_EXCLUDED_NAMESPACES: ''
