apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeledger-config
data:
  KL_COST_MODEL: 'CUMULATIVE_RATIO'
  KL_BILLING_HOURLY_RATE: '0.0'
  KL_BILLING_CURRENCY_SYMBOL: '$'
  KL_K8S_API_ENDPOINT: 'https://kubernetes.default'
  KL_K8S_API_VERIFY_SSL: 'true'
  KL_K8S_CACERT: '/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  KL_INCLUDED_NAMESPACES: ''
  KL_EXCLUDED_NAMESPACES: ''
