---
apiVersion: v1
kind: Pod
metadata:
  name: "kubeledger-test-connection"
  labels:
    app.kubernetes.io/name: kubeledger
    app.kubernetes.io/instance: kubeledger
spec:
  containers:
    - name: wget
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo 'waiting 60s';
          sleep 60;
          wget 'kubeledger:80';
          echo done;   
  restartPolicy: Never
