name: GHCR Image
on:
  push:
    tags:
      - v*
jobs:
  build_ghcr_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Build and push Docker image
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          export IMAGE_TAG=$(echo $GIT_TAG | sed 's/v//')
          docker build . --file Dockerfile --tag ghcr.io/realopslabs/kubeledger:$IMAGE_TAG
          docker tag ghcr.io/realopslabs/kubeledger:$IMAGE_TAG ghcr.io/realopslabs/kubeledger:latest
          echo "$GH_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/realopslabs/kubeledger:$IMAGE_TAG
          docker push ghcr.io/realopslabs/kubeledger:latest
